//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend_proyectando.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProyectoFase
    {
        public long id_proyecto_fase { get; set; }
        public long id_faseProceso { get; set; }
        public long id_proyecto { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public Nullable<System.DateTime> fecha_fin { get; set; }
    
        public virtual FaseProceso FaseProceso { get; set; }
        public virtual Proyecto Proyecto { get; set; }
    }
}
