//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace backend_proyectando.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono
    {
        public long id_telefono { get; set; }
        public string documentoCliente { get; set; }
        public Nullable<long> id_tipo_telefono { get; set; }
        public string numero { get; set; }
        public Nullable<bool> activo { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual TipoTelefono TipoTelefono { get; set; }
    }
}
